version: "3.9"

services:
  pdf_service:
    build: ./pdf_service
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    volumes:
      - ./pdf_service:/app

  rag_module:
    build: ./rag_module
    ports:
      - "8001:8001"
    environment:
      - ENV=development
    volumes:
      - ./rag_module:/app

  aws_service:
    build: ./aws_service
    ports:
      - "8002:8002"
    environment:
      - ENV=development
    volumes:
      - ./aws_service:/app

  metrics_lambda:
    build: ./metrics_lambda
    ports:
      - "9000:9000"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    volumes:
      - ./metrics_lambda:/app
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
